/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumList: typeof import('./components/AlbumList.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    ItemPhoto: typeof import('./components/ItemPhoto.vue')['default']
    ItemPhotoDetail: typeof import('./components/ItemPhotoDetail.vue')['default']
    PhotoSearch: typeof import('./components/PhotoSearch.vue')['default']
    PreviewPhoto: typeof import('./components/PreviewPhoto.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    TheMain: typeof import('./components/TheMain.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
  }
}
